# Databricks notebook source
# MAGIC %sql
# MAGIC create table llm.rag.docs_text_multiple_model(
# MAGIC     id bigint generated by default as identity,
# MAGIC     file_name string,
# MAGIC     model_number string,
# MAGIC     manual_version string,
# MAGIC     text string
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE TABLE llm.rag.docs_track_multiple_model(
# MAGIC     file_name STRING,
# MAGIC     model_number STRING,
# MAGIC     manual_version STRING,
# MAGIC     load_timestamp TIMESTAMP
# MAGIC );